services:
  - type: web
    name: longreviewfrontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/long-review/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
